---
kind: pipeline
type: kubernetes
name: hello-world

steps:
- name: build-hello-world
  image: plugins/docker
  settings:
    dockerfile: ./mysql-example/Dockerfile
    username:
      from_secret: prod_docker_username
    password:
      from_secret: prod_docker_password
    repo: italosantos/nodejs-mysql
    tags: latest
  when:
    event:
      - push
    branch:
      - master

- name: helm-deploy
  image: pelotech/drone-helm3
  settings:
    namespace: helloworld
    helm_command: upgrade
    chart: ./helm/helloworld
    release: helloworld
    api_server:
      from_secret: prod_api_server
    kubernetes_token:
      from_secret: prod_kubernetes_token
  when:
    event:
      - push
    branch:
      - master